// Pre-baked demo using the real KKR vs PBKS API response structure
export const BMS_DEMO = {
  eventName: "KOLKATA KNIGHT RIDERS VS PUNJAB KINGS - TATA IPL 2026",
  venueName: "Eden Gardens: Kolkata",
  location: "Kolkata",
  showDate: "Monday, 6 Apr",
  showTime: "07:30 PM",
  bannerUrl: "https://assets-in.bmscdn.com/nmcms/events/banner/desktop/media-desktop-kolkata-knight-riders-vs-punjab-kings-tata-ipl-2026-0-2026-3-13-t-10-27-8.jpg",
  priceMin: 1200,
  priceMax: 8500,
  currencySymbol: "₹",
  available: 200,
  totalStands: 20,
  soldOut: 0,
  activeStands: 20,
  stands: [
    { id: "T708", name: "B Premium BKT TYRES PAV", type: "SEATS", seatLayout: "Y", status: "AVAILABLE", qty: 148, available: 148, total: 346, fill: 57, price: 8500, perks: ["Food Buffet & Soft Beverages", "KKR Fan Jersey", "KKR Scarf"] },
    { id: "T709", name: "Club House Lower Tier", type: "SEATS", seatLayout: "Y", status: "AVAILABLE", qty: 226, available: 226, total: 451, fill: 50, price: 8000, perks: [] },
    { id: "T746", name: "L Block PREMIUM VIDA PAV", type: "SEATS", seatLayout: "Y", status: "AVAILABLE", qty: 54, available: 54, total: 500, fill: 89, price: 5000, perks: ["Food Box", "KKR Fan Jersey"] },
    { id: "T748", name: "L Block JAC OLIVOL PAV", type: "SEATS", seatLayout: "Y", status: "AVAILABLE", qty: 39, available: 39, total: 340, fill: 89, price: 3300, perks: [] },
    { id: "T714", name: "B Block BKT TYRES PAV", type: "SEATS", seatLayout: "Y", status: "AVAILABLE", qty: 95, available: 95, total: 401, fill: 76, price: 3500, perks: [] },
    { id: "T711", name: "Club House Upper Tier", type: "SEATS", seatLayout: "Y", status: "AVAILABLE", qty: 3, available: 3, total: 302, fill: 99, price: 3000, perks: [] },
    { id: "T728", name: "F Block JIO PAV", type: "SEATS", seatLayout: "Y", status: "AVAILABLE", qty: 40, available: 40, total: 243, fill: 84, price: 2000, perks: [] },
    { id: "T718", name: "C Block RR KABEL PAV", type: "SEATS", seatLayout: "Y", status: "AVAILABLE", qty: 8, available: 8, total: 209, fill: 96, price: 2000, perks: [] },
    { id: "T732", name: "G Block VIDA PAV", type: "SEATS", seatLayout: "Y", status: "AVAILABLE", qty: 100, available: 100, total: 243, fill: 59, price: 2000, perks: [] },
    { id: "T742", name: "K Block JIO PAV", type: "SEATS", seatLayout: "Y", status: "AVAILABLE", qty: 50, available: 50, total: 306, fill: 84, price: 2000, perks: [] },
    { id: "T716", name: "B1 Block BKT TYRES PAV", type: "GENERAL", seatLayout: "N", status: "AVAILABLE", qty: 10, available: null, total: null, fill: null, price: 1500, perks: [] },
    { id: "T722", name: "D Block VIDA PAV", type: "GENERAL", seatLayout: "N", status: "AVAILABLE", qty: 10, available: null, total: null, fill: null, price: 1500, perks: [] },
    { id: "T720", name: "C1 Block RR KABEL PAV", type: "GENERAL", seatLayout: "N", status: "AVAILABLE", qty: 8, available: null, total: null, fill: null, price: 1200, perks: [] },
    { id: "T744", name: "K1 Block JIO PAV", type: "GENERAL", seatLayout: "N", status: "SOLD OUT", qty: 0, available: null, total: null, fill: null, price: 1200, perks: [] },
  ],
  canonicalUrl: "https://in.bookmyshow.com/sports/kolkata-knight-riders-vs-punjab-kings-tata-ipl-2026/ET00491227",
}

export const DISTRICT_DEMO = {
  eventName: "SRH Fan Meet & Greet",
  venueName: "Rajiv Gandhi International Cricket Stadium",
  location: "Hyderabad",
  showDate: "Sun, 6 Apr",
  showTime: "05:00 PM",
  bannerUrl: "",
  priceMin: 999,
  priceMax: 5000,
  currencySymbol: "₹",
  available: 340,
  totalStands: 4,
  soldOut: 1,
  activeStands: 3,
  isQueueActive: false,
  stands: [
    { id: "s1", name: "VIP Lounge", type: "SEATS", status: "AVAILABLE", qty: 12, price: 5000, perks: ["Early Bird Phase 1", "Phase 2"] },
    { id: "s2", name: "Premium Stand", type: "SEATS", status: "AVAILABLE", qty: 48, price: 2500, perks: [] },
    { id: "s3", name: "General Stand", type: "GENERAL", status: "AVAILABLE", qty: 280, price: 999, perks: [] },
    { id: "s4", name: "Fan Pit", type: "GENERAL", status: "SOLD OUT", qty: 0, price: 999, perks: [] },
  ],
}
